---
title: "Indian Super League Season Transfers 23/24 "
author: "Hari Krishna"
format: html
execute:
  echo: false
server: shiny
---

```{r setup,include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 
```

From the inception in 2013 season after season the league keeps improving.The introduction of promotion of team(Punjab FC) from I-league this season opens up lot of opportunities for the players in the league

Let's look at how the teams have fared in the Transfer market for the 23/24 season

```{r}
#| context: setup
library(reactable)
library(tidyverse)
library(reactablefmtr)
library(shiny)
library(bslib)
data<-read.csv("All_Transfers.csv",check.names = F)
data$`Market values`<-gsub("<[^>]+>", "", data$`Market values`)
data$Fee<-gsub("<[^>]+>", "", data$Fee)
```

```{r}
selectInput("team","Select Team",choices=unique(data$Team_Name))
selectInput("transfer","Select Transfer",choices=unique(data$Transfer_Type))
reactableOutput("table")

```

```{r}
#| context: server
output$table <- renderReactable({
reactable(
  data %>% filter(input$team==Team_Name,input$transfer==Transfer_Type) %>% select(Club_Logo_URL,`Player Name`,everything()),
 pagination = T,
  fullWidth = T,
  striped = T,
  bordered = T,
  highlight = T,
  compact = T,
  columns = list(
    `Player Name`= colDef(align="center",width=1000,sticky = "right"),
    Age=colDef(align="center",width=200),
    Position=colDef(align="center",width=200),
    Fee=colDef(align="center",width=200),
    Pos=colDef(align="center",width=100),
    `Market values`=colDef(align="center",width=200),
    Team_Name=colDef(show=F),
    Transfer_Type=colDef(show=F),
    Club_Logo_URL = colDef(
      name = "Team",
      align = "center",
      cell = embed_img( width = "55px",height="35px")
    )
    #Club_Logo_URL = colDef(cell = embed_img(width = "20px", height = "30px"))
  )
)
})






```
